---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: helloworld
  namespace: my-awesome-project
spec:
  selector:
    matchLabels:
      app: helloworld
  action: DENY
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/my-awesome-project/sa/sleep
    to:
    - operation:
        methods:
        - GET